version: '3.6'
services:

  php-l8:
    build:
      context: .
      dockerfile: php.Dockerfile
    container_name: php-fpm
    volumes:
      - ./public:/var/www/html

  db:
    image: mysql:latest
    command: --tmp_table_size=8G --max_heap_table_size=8G
    container_name: mysql_db
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./mysql:/var/lib/mysql

volumes:
  mysql: {}
